name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node.js environment...
      uses: actions/setup-node@v2-beta
#       with:
#           version: 12

    - name: GitHub Action for Yarn...
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: install
   
    - name: Creating Build...
      run: yarn build   
      
    - name: Installing Surge... 
      run: npm install -g surge    
    
    - name: Deploying Surge...
      run: surge ./build msr-bootcamp-react-ts-quiz-app.surge.sh/ --token ${{ secrets.SURGE_TOKEN }}
     
